title: Undercooked release archive
description: >-
url: "https://qguv.github.io/undercooked"

theme: minima
plugins:
  - jekyll-feed

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
      permalink: /play/:title/
      has_pocket_build: true
