#!/bin/sh
set -e
export PIPENV_VENV_IN_PROJECT=1

if [ "$1" = clean ]; then
  echo removing build output
  rm -rf obj
  exit 0
fi

mkdir -p obj

if ! hash pipenv 2>/dev/null; then
  if ! hash pip 2>/dev/null; then
    echo please install pipenv or pip
    exit 1
  fi

  echo installing pipenv
  pip install -qq pipenv
fi

(
  cd meta
  if ! [ -d .venv ]; then
    echo installing jinja2
    poetry install
  fi

  echo rendering build.ninja
  pipenv run ./jinja2_render.py .. < build.ninja.j2 > ../obj/build.ninja
)

echo running ninja
ninja -f obj/build.ninja "$@"
