#!/bin/sh
set -e

ROM=obj/main.gb

[ -e build.ninja ] || ./configure

ninja "$ROM" >&2

[ -e obj/debugmsg.txt ] && rm obj/debugmsg.txt

BGB_CONFIG_PATH=/dev/null \
BGB_SAVE_CONFIG=false \
BGB_DEBUGMSG_DIR=obj \
bgb -nobatt -set StartDebug=1 -set DebugMsgFile=1 -set DebugEcho=1 "$ROM" 2>/dev/null

[ -e obj/debugmsg.txt ] && cat obj/debugmsg.txt
